### ISSUE TITLE
Portal - Development of features to the new version

### ISSUE THREAD

**Issue by joaorafaelalmeida** [EHDEN/ehden-roadmap#31]
New features:

- Possibility of customizing pages using a WordPress instance.
- Allowing users without credentials to access the first layer of the system (disabled until someone request to activate it)
- Extra question in the join form to help community manager identify the new users.
- New type of customization of the "Recent publication" box. Now the community manager can define a PubMed query in the community.
- Refactoring the plugins in order to be more flexible, and maybe allowing to iframe applications that were not possible before.

**Comment by keesvanbochove** [comment]
@joaorafaelalmeida is there somewhere we can test the access without login? (Especially to view database fingerprints?)
